language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-python-dev
sudo: false
install:
  - deactivate
  - pip install --user psycopg2 matplotlib
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
