language: python
python:
  - 2.7
addons:
  apt:
    packages:
    - libboost-dev
sudo: false
install:
  - pip install psycopg2 mapnik2 matplotlib
  - python bootstrap.py
  - bin/buildout
script:
  - bin/test
