language: python
cache: pip
python:
  - 2.7
sudo: false
notifications:
  irc:
    channels: "irc.freenode.org#nens"
    on_success: change
  email: false
install:
  - pip install matplotlib psycopg2 mapnik
  - python bootstrap.py
#  - bin/buildout
script:
#  - bin/test
  - echo 'hallo'
